### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by mark-halter** [nfejes/stereo-bundle-adjustment#1]
Hi there,

Can you confirm whether this code works? I am looking for something like this. Have you used it in an application?

**Comment by nfejes** [comment]
I think it works to some extent but you are probably better off starting from scratch with the Ceres solver examples. This repo was for a code we used in a class project and it is basically just the SBA example tuned for our data set. This repo was abandoned as we moved to someone else's repo, iirc.
